logging:
  level:
    root: INFO
    com.auth.server: DEBUG

server:
  port: 8081

spring:
  data:
    cassandra:
      keyspace-name: authorization_keyspace
      contact-points: localhost
      local-datacenter: datacenter1
jwt:
  password: <password>
  alias: <alias>
  privateKey: <privateKeyFileName>.jks