name: build-project

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - master
      - develop
jobs:
  prepare:
    if: ${{github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - id: check-branch-name
        run: |
          if [[ ${{ github.ref_name }} =~ ^feature.*$ ]]; then
            echo "Setting branch name output"
            echo ::set-output name=branch::feature
          else
            echo "Branch name not feature"
          fi
      - run: echo ${{steps.check-branch-name.outputs.branch}}
    outputs:
      branch-name: ${{steps.check-branch-name.outputs.branch}}
  feature:
    needs: prepare
    if: ${{needs.prepare.outputs.branch-name == 'feature'}}
    env:
      MODE: feature
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking out revisions from gitHub repo"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: echo "Java initialization done"
      - run: mvn -B clean package --file pom.xml
      - run: echo "All steps ran successfully Job completed for branch"
  develop:
    needs: prepare
    if: ${{github.ref_name == 'develop'}}
    env:
      MODE: develop
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking out revisions from gitHub repo"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: echo "Java initialization done"
      - run: mvn -B clean package --file pom.xml
      - run: echo "All steps ran successfully Job completed for branch"
  master:
    needs: prepare
    if: ${{github.ref_name == 'master'}}
    env:
      MODE: master
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking out revisions from gitHub repo"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: echo "Java initialization done"
      - run: mvn -B clean package --file pom.xml
      - run: echo "All steps ran successfully Job completed for branch"
  pull-requets:
    if: ${{github.event_name == 'pull_request'}}
    env:
      MODE: ${{github.base_ref}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking out revisions from gitHub repo"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: echo "Java initialization done"
      - run: mvn -B clean package --file pom.xml
      - run: echo "All steps ran successfully Job completed for branch"